export interface DocumentStorage {
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  // Returns the HTTP response for an already-authorised download.
  download(key: string, filename: string, contentType: string): Promise<Response>;
  delete(key: string): Promise<void>;
  deletePrefix(prefix: string): Promise<void>;
}

const KEY_PATTERN = /^documents\/[A-Za-z0-9_-]+\/[0-9a-f-]{36}$/;
const PREFIX_PATTERN = /^documents\/[A-Za-z0-9_-]+\/$/;

// Keys are generated by the app; these checks stop a bad key from ever reaching a path or bucket.
export function assertValidKey(key: string) {
  if (!KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
}

export function assertValidPrefix(prefix: string) {
  if (!PREFIX_PATTERN.test(prefix)) throw new Error("Invalid storage prefix");
}

export function documentKey(userId: string, id: string) {
  return `documents/${userId}/${id}`;
}

export function userPrefix(userId: string) {
  return `documents/${userId}/`;
}
