import "server-only";
import path from "node:path";
import PDFDocument from "pdfkit";
import type { PackData } from "./load";

export const PACK_DISCLAIMER =
  "Generated by RentCert from information entered by the account holder. This document is not a certificate and does not confirm legal compliance.";

const FONT_DIR = path.join(process.cwd(), "assets", "fonts");
const REGULAR = "NotoSans";
const BOLD = "NotoSans-Bold";

// Harbour theme colours, matching src/app/globals.css.
const COLOURS = { ink: "#17312f", muted: "#4f6461", line: "#dde7e2", band: "#f3f6f2" };
const MARGIN = 50;
const FOOTER_SPACE = 48;

type Column = { header: string; width: number };

// Renders a compliance pack from plain data. No database access and no request handling here.
export class CompliancePackGenerator {
  private readonly doc: PDFKit.PDFDocument;

  constructor(private readonly data: PackData) {
    this.doc = new PDFDocument({
      size: "A4",
      margins: { top: MARGIN, bottom: MARGIN + FOOTER_SPACE, left: MARGIN, right: MARGIN },
      bufferPages: true,
      info: { Title: `RentCert Compliance Pack – ${data.property.street}`, Creator: "RentCert", Producer: "RentCert" },
    });
    this.doc.registerFont(REGULAR, path.join(FONT_DIR, "NotoSans-Regular.ttf"));
    this.doc.registerFont(BOLD, path.join(FONT_DIR, "NotoSans-Bold.ttf"));
  }

  async generate(): Promise<Buffer> {
    const chunks: Buffer[] = [];
    const done = new Promise<Buffer>((resolve, reject) => {
      this.doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      this.doc.on("end", () => resolve(Buffer.concat(chunks)));
      this.doc.on("error", reject);
    });

    this.cover();
    this.doc.addPage();
    this.propertyDetails();
    this.summary();
    this.history();
    this.documents();
    this.footers();
    this.doc.end();
    return done;
  }

  private get width() {
    return this.doc.page.width - MARGIN * 2;
  }

  private cover() {
    const { doc, data } = this;
    doc.font(BOLD).fontSize(28).fillColor(COLOURS.ink).text("RentCert Compliance Pack", MARGIN, 200);
    doc.moveDown(1.5);
    doc.font(REGULAR).fontSize(12).fillColor(COLOURS.muted).text("Property:");
    doc.font(BOLD).fontSize(16).fillColor(COLOURS.ink).text(data.property.street);
    doc.font(REGULAR).fontSize(14).text(data.property.locality);
    doc.moveDown(1.5);
    doc.font(REGULAR).fontSize(12).fillColor(COLOURS.muted).text("Generated:");
    doc.font(REGULAR).fontSize(14).fillColor(COLOURS.ink).text(data.generatedOn);
  }

  private heading(text: string) {
    this.ensureSpace(60);
    this.doc.moveDown(0.8).font(BOLD).fontSize(15).fillColor(COLOURS.ink).text(text, MARGIN);
    this.doc.moveDown(0.4);
  }

  private note(text: string) {
    this.doc.font(REGULAR).fontSize(9).fillColor(COLOURS.muted).text(text, MARGIN, undefined, { width: this.width });
    this.doc.moveDown(0.5);
  }

  private propertyDetails() {
    const { data } = this;
    this.heading("Property details");
    const rows: [string, string][] = [
      ["Address", `${data.property.street}, ${data.property.locality}`],
      ...(data.property.nickname ? ([["Nickname", data.property.nickname]] as [string, string][]) : []),
      ["Lease start", data.property.leaseStart ?? "Not entered"],
      ...(data.property.archived ? ([["Status", "Archived"]] as [string, string][]) : []),
    ];
    this.table([{ header: "", width: 120 }, { header: "", width: this.width - 120 }], rows, { headerRow: false });
  }

  private summary() {
    const { data } = this;
    this.heading("Compliance summary");
    this.note(
      "Dates are calculated from the dates entered in RentCert. Confirm the requirements that apply with a licensed provider or the official guidance for the property's state or territory.",
    );
    if (data.isGeneric) {
      this.note(`General reminder schedule: RentCert has not yet researched ${data.property.state} rules.`);
    }
    const w = this.width;
    this.table(
      [
        { header: "Requirement", width: w * 0.3 },
        { header: "Last completed", width: w * 0.22 },
        { header: "Next due", width: w * 0.22 },
        { header: "Status", width: w * 0.26 },
      ],
      data.summary.map((row) => [row.name, row.lastCompleted, row.nextDue, row.status]),
    );
    const sources = [...new Set(data.summary.flatMap((row) => (row.source ? [row.source] : [])))];
    if (sources.length > 0) this.note(`Intervals based on: ${sources.join("; ")}.`);
  }

  private history() {
    const { data } = this;
    this.heading("Compliance history");
    if (data.history.length === 0) return this.note("No compliance records.");
    const w = this.width;
    this.table(
      [
        { header: "Requirement", width: w * 0.24 },
        { header: "Completed", width: w * 0.19 },
        { header: "Next due", width: w * 0.19 },
        { header: "Provider", width: w * 0.22 },
        { header: "Licence", width: w * 0.16 },
      ],
      data.history.map((row) => [row.requirement, row.completed, row.nextDue, row.provider, row.licence]),
    );
  }

  private documents() {
    const { data } = this;
    this.heading("Documents");
    if (data.documents.length === 0) return this.note("No documents uploaded.");
    this.note("Original certificates are not included in this pack. The fingerprint (SHA-256) identifies each file.");
    const w = this.width;
    this.table(
      [
        { header: "Document", width: w * 0.28 },
        { header: "Compliance type", width: w * 0.2 },
        { header: "Check completed", width: w * 0.16 },
        { header: "Uploaded", width: w * 0.16 },
        { header: "Fingerprint", width: w * 0.2 },
      ],
      data.documents.map((row) => [row.filename, row.requirement, row.recordCompleted, `${row.uploaded} (${row.size})`, row.fingerprint]),
    );
  }

  private ensureSpace(height: number) {
    const bottom = this.doc.page.height - this.doc.page.margins.bottom;
    if (this.doc.y + height > bottom) this.doc.addPage();
  }

  private table(columns: Column[], rows: string[][], { headerRow = true } = {}) {
    const { doc } = this;
    const padding = 4;
    const fontSize = 9;

    const rowHeight = (cells: string[], font: string) => {
      doc.font(font).fontSize(fontSize);
      return Math.max(...cells.map((cell, i) => doc.heightOfString(cell || " ", { width: columns[i].width - padding * 2 }))) + padding * 2;
    };

    const drawRow = (cells: string[], font: string, fill?: string) => {
      const height = rowHeight(cells, font);
      this.ensureSpace(height);
      const top = doc.y;
      if (fill) doc.rect(MARGIN, top, this.width, height).fill(fill);
      let x = MARGIN;
      cells.forEach((cell, i) => {
        doc.font(font).fontSize(fontSize).fillColor(COLOURS.ink).text(cell, x + padding, top + padding, { width: columns[i].width - padding * 2 });
        x += columns[i].width;
      });
      doc.moveTo(MARGIN, top + height).lineTo(MARGIN + this.width, top + height).lineWidth(0.5).strokeColor(COLOURS.line).stroke();
      doc.x = MARGIN;
      doc.y = top + height;
      return height;
    };

    const header = () => drawRow(columns.map((column) => column.header), BOLD, COLOURS.band);
    if (headerRow) header();
    for (const row of rows) {
      const needed = rowHeight(row, REGULAR);
      if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
        if (headerRow) header(); // repeat the header on each new page
      }
      drawRow(row, REGULAR);
    }
    doc.moveDown(0.5);
  }

  private footers() {
    const { doc } = this;
    const range = doc.bufferedPageRange();
    for (let index = range.start; index < range.start + range.count; index++) {
      doc.switchToPage(index);
      const bottomMargin = doc.page.margins.bottom;
      doc.page.margins.bottom = 0; // writing inside the margin must not create a new page
      const y = doc.page.height - MARGIN - 30;
      doc.font(REGULAR).fontSize(8).fillColor(COLOURS.muted);
      doc.text(PACK_DISCLAIMER, MARGIN, y, { width: this.width - 70 });
      doc.text(`Page ${index + 1} of ${range.count}`, MARGIN + this.width - 70, y, { width: 70, align: "right" });
      doc.page.margins.bottom = bottomMargin;
    }
  }
}
